KatLab-MiyazakiUniv/etrobocon2021

README.md

- README.mdにビルド方法、テストの実行方法、その他を書いた。

Close #3 Update: READMEにビルド、テスト、その他を記述

---

app.cfg
app.cpp
app.h

- mainタスク以外の全てのタスクを削除
- 余計な `include` 文を削除

close #21 余計なタスクを削除

---

Makefile.inc
app.cfg

- app.cfgの`#include "app.h"`が削除されていたので，修復
- Makefileにコメントアウトを追記

close #23 開発環境の修正

---

Makefile.inc
module/Mileage.cpp
module/Mileage.h
test/MileageTest.cpp

close #17 走行距離を計算する

---

module/Mileage.cpp
module/Mileage.h
test/MileageTest.cpp

- シングルトンクラスではなく静的クラスに変更した
- 定数の名前をコーディング規約に準じたものに変更した

close #38 Mileageクラスのmakeが通らない問題の解決

---

Makefile.inc

close #45 Makefileの修正

---

.github/workflows/build-check.yaml
Dockerfile
entrypoint.sh
module/Controller.cpp
module/Controller.h
module/EtRobocon2021.cpp
module/LineTracer.cpp
module/LineTracer.h
module/Measurer.h
test/dummy/Clock.h
test/dummy/Motor.cpp
test/dummy/Motor.h

- LineTracer.h、LineTracer.cppの追加
- Clock.h（ダミー）の追加
- Motor.h、Motor.cpp（ダミー）の修正
- LineTracerクラスのテストファイル削除
- Controller.h、Controller.cppの修正
https://user-images.githubusercontent.com/83375723/121863595-fbb80000-cd36-11eb-9b64-ddfc871c63df.mp4
追記
lineTracer.run(1625.34, 20, 30, PidGain(0.8, 0.01, 0.01));
controller.sleep(2000);
lineTracer.run(594.506, 20, 30, PidGain(0.8, 0.01, 0.01));
controller.sleep(2000);
lineTracer.run(690.288, 20, 30, PidGain(0.8, 0.01, 0.01));
controller.sleep(2000);
lineTracer.run(511.724, 20, 30, PidGain(0.8, 0.01, 0.01));
controller.sleep(2000);
lineTracer.run(1709.7, 20, 30, PidGain(0.8, 0.01, 0.01));
controller.sleep(2000);
lineTracer.run(309.562, 20, 30, PidGain(0.8, 0.01, 0.01));
controller.sleep(2000);
lineTracer.run(807.404, 20, 30, PidGain(0.8, 0.01, 0.01));

close #34 ライントレーサークラス追加

---

module/BingoArea.cpp
module/BingoArea.h
module/BlockCircle.cpp
module/BlockCircle.h
module/CenterMark.cpp
module/CenterMark.h
module/CrossCircle.cpp
module/CrossCircle.h
module/Measurer.cpp
module/Measurer.h
module/Node.cpp
module/Node.h
test/BingoAreaTest.cpp
test/dummy/etroboc_ext.cpp
test/dummy/etroboc_ext.h

Measurer.h、Measurer.cppにコース情報取得用APIを追加
Nodeクラス、BlockCircleクラス、CrossCircleクラス、CenterMarkクラス、BingoAreaクラスを追加
BingoAreaクラスのテストコードを追加
テストコードにて競技規約p26の状態に初期化できていることを確認
[BlockIdの振り分け](https://github.com/KatLab-MiyazakiUniv/etrobocon2021/files/6782932/BlockId.pdf)
[コース情報の取得](https://github.com/ETrobocon/etrobo/wiki/sim_extended_api)

close#81 ビンゴエリアクラス

---

module/Controller.cpp
module/Controller.h
module/HorizonArm.cpp
module/HorizonArm.h
module/Measurer.cpp
module/Measurer.h

追加ファイル
- HorizonArm.cpp
- HorizonArm.h
編集ファイル
- Measurer.h
- Mesaurer.cpp
- Controller.h
- Controller.cpp
回頭させて、Measurerのカウントで値を検証
改善前は、-48 ~ -1の範囲を動いていた。
改善後は、-46 ~ -40の範囲を動いていた。
-46~-44を中心に動いていた
ライントレースエリアでも検証した。
ノートPC環境：初回のカーブでコースアウト１回、スタート時回転２回
研究室環境：完走４回、スタート時回転１回
改善前
https://user-images.githubusercontent.com/83441177/126899639-0c970ef9-d64a-437d-a563-adb3fc09b19c.mp4
改善後
https://user-images.githubusercontent.com/83441177/126899644-6df40add-0284-4fb9-93cb-e58bbea3c964.mp4
ラントレースエリア
https://user-images.githubusercontent.com/83441177/127105923-1e294fad-9463-4f0b-8267-468ecdfc45a3.mp4

close #93 アームを水平に保つ  

---

app.cfg
app.cpp
app.h

- アームを水平に保つarm_taskを追加
- 経路計算を行うタスクroute_taskを追加
HorizonArmインスタンスを持ち，HrizonArm::keepArmを繰り返してアームを常に水平に保つタスク
ビンゴエリアの経路計画を行うタスク
ライントレースエリア攻略と並行して経路計画を行い，ブロックを全て運ぶまでの経路を算出した時点でタスクを終了する

close #98 タスク設計をする

---

.github/workflows/sim-test.yaml

- GitHub Self Hosted Runner によるシミュレータ実行機能の追加
- 走行に成功した場合、プルリクのコメントに走行コメントを記述する
[このプルリク](https://github.com/KatLab-MiyazakiUniv/etrobocon2021/pull/92/checks?check_run_id=3073832833)
[test: わざとゴールしない Simulator Test #62](https://github.com/KatLab-MiyazakiUniv/etrobocon2021/actions/runs/1032720123)

close #4 シミュレータの自動実行

---

module/RoutePlanner/RoutePlanner.cpp
module/RoutePlanner/RoutePlanner.h
test/RoutePlannerTest.cpp

RoutePlanner.h
RoutePlanner.cpp
RoutePlannerTest.cpp
RoutePlannerクラスに経路計算の処理を追加
全てのブロックサークルにブロックが置かれているかのテストコードの作成
全てのブロックサークルにブロックが置かれていることを確認するテストを行う。
全ての交点サークルにブロックが置かれていないことを確認するテストを行う。
走行体の方向について「動作変換」チケットのDirectionの更新を反映したうえで動作確認。(このブランチでは、更新前の定義になっている)
グーグルテストの通過を確認できた。

close #115 経路計画の具体化

---

.github/workflows/sim-test.yaml
README.md

- シミュレータテストを実行した後、シミュレータが生成したPNGファイルをMP4に変換するようにした
- プルリクのシミュレータテストの結果を通知する際、動画のリンクも添付するようにした
- 各ゲートの通過状況を表形式に変更
- READMEにシミュレータテストのステータスバッジを追加
このプルリク及び、以下のプルリクを確認すること
[【レビュー対象外】シミュレータテストの動画添付 #118](https://github.com/KatLab-MiyazakiUniv/etrobocon2021/pull/118)
ビンゴエリアの状況も反映したかったが、CSVファイルの見方が分からず（ドキュメントを見つけられなかった）実際にシミュレータを動かしてもビンゴエリア手前の青線部分でコースアウトが多発しため、一旦放置。
[Ticket 113](https://github.com/KatLab-MiyazakiUniv/etrobocon2021/pull/117)のコードで照明条件を変え計171回実行したがビンゴエリアまで移動し、ブロックの有効移動を果たしたのは1回のみ。
（自分の設定ミスっているかも？？？）

close #36 シュミレータの動画を添付する

---

module/CourseInfo/CourseInfo.cpp
module/CourseInfo/CourseInfo.h
module/CourseInfo/Robot.h
module/RoutePlanner/BlockSelector.cpp
module/RoutePlanner/BlockSelector.h
module/RoutePlanner/DestinationList.cpp
module/RoutePlanner/DestinationList.h
module/RoutePlanner/RouteCalculator.cpp
module/RoutePlanner/RouteCalculator.h
module/RoutePlanner/RoutePlanner.cpp
module/RoutePlanner/RoutePlanner.h
test/BingoAreaTest.cpp
test/BlockSelectorTest.cpp
test/DestinationListTest.cpp
test/MotionConverterTest.cpp
test/RouteCalculatorTest.cpp
test/RoutePlannerTest.cpp

BingoAraeをCourseInfoに変更
~# 動作テスト~
~## 実験方法~
~## 実験データ~
~|  修正前  |  修正後  |~
~| ---- | ---- |~
~|  -  |  -  |~
~|  -  |  -  |~
~## 実験結果~
~## 添付資料~

close #134 BingoAreaをCourseInfoに変更

---

module/Motion/Mileage.h

- Mileage.hのprivateにコンストラクタを追加

close #135 Mileage.hのprivateにコンストラクタを記述

---

module/BingoMotion/BlockThrower.cpp
module/BingoMotion/BlockThrower.h
module/Motion/Rotation.cpp
module/Motion/Rotation.h

- Rotationクラスのピボットターンに、動作前のタイヤの回転数を考慮する処理を追加
- Rotationクラス、BlockThrowerクラスの不要なstaticを削除
|  -  |  -  |
|  -  |  -  |

close #156 ピボットターンの修正

---

module/Motion/Rotation.cpp

Rotation.cpp 
軸足（ leftCount, rightCount）に今までの累積距離を追加
https://user-images.githubusercontent.com/83230897/131436641-6806b0f9-b63a-4213-abe2-9ec28a381c5e.mp4

close #165 ピボットターンのバグ修正

---

.github/workflows/sim-test.yaml

CIのシミュレータテストでブロックの配置をランダムにするようにした
このプルリクのCIの結果を参照すること

close #179 CIのシミュレータテストでブロックの配置をランダムにする

---

module/BingoMotion/InCrossLeft.cpp
module/BingoMotion/InCrossRight.cpp

- 交点内左折と交点内右折のパラメータの調整
「交点間移動→交点内左折→交点間移動→交点内右折→交点間移動」を，ブロックがない場合とある場合でそれぞれ10回ずつ行い，動作を確認する．
成功回数/実験回数
|  ブロック無し  |  ブロックあり  |
|  10/10  |  10/10  |
https://user-images.githubusercontent.com/56989154/132174367-14b9aab0-6cca-49d2-a999-e7ef9ec31450.mp4
https://user-images.githubusercontent.com/56989154/132174431-abf29ced-05e2-4b0a-8712-13eff810a0a3.mp4

close #161, close #162 交点内左折の調整，交点内右折の調整

---

module/BingoMotion/BlockThrower.cpp

- 投げ入れ設置時の後退を打ち消すために直進を追加
|  -  |  -  |
|  -  |  -  |

#141 投げ入れ設置の調整

---

module/BingoMotion/BlackBlockCarrier.cpp
module/BingoMotion/ToCrossMotion.cpp

交点間移動と黒ブロック運搬の精度調整
|  -  |  -  |
|  -  |  -  |

#195 黒ブロック運搬と交点間移動の精度調整

---

module/BingoMotion/DirectionChanger.cpp

close #208 方向転換の不要な処理を削除

---

module/BingoMotion/BlackBlockCarrier.cpp

- 設置位置を上方に修正した
|  -  |  -  |
|  -  |  -  |

close #237 黒ブロック設置の調整

---

module/BingoMotion/BlockThrower.cpp

投げ入れ設置動作内にprintfを追加
|  -  |  -  |
|  -  |  -  |

close #233 投げ入れ設置の不具合調査・解消

---

module/BingoMotion/BlockThrower.cpp

1. 投げ入れ設置で異常な挙動を防ぐためのprintfの出力を減らした。投げ入れ設置の投げ入れ距離が短くなっていたが、出力文字数を減らすことで改善した。原因は不明(処理時間による？)。
複数の環境で、20回以上実行した結果、投げ入れ距離が足りず、設置したサークルの近くを通行した際、サークル外にずらしてしまっていた現象が少なくなっていることを確認した。

close #249 光環境・不具合に対する諸調整

---

module/LineTraceArea.cpp

- PID、走行距離の調整
- 試走会で20回走らせる
- 平均ゴールタイム：15.885
- ゴール率：80％（16/20）
試走会ゴール率
調整前：65.95％（31/47）→　調整後：80％（16/20）

close #248 ライントレースエリア最終調整

---

module/BingoMotion/BlockPivotTurn.cpp

各パラメータを調整した。
|  -  |  -  |
|  -  |  -  |

close #247 ピボットターン設置の最終調整

---

module/BingoMotion/BlockPivotTurn.cpp

左右、二回目の回頭角度の調整
|  -  |  -  |
|  -  |  -  |

ピボットターン設置のパラメータ調整
