KatLab-MiyazakiUniv/etrobocon2021

module/CourseInfo.cpp, module/CourseInfo.h
- iostreamをincludeするとmakeに失敗するため、`std::cout` を `printf` に変更した
- MileageクラスをMakefile.incから除外した場合に、make, gtest_allがパスすることを確認した (※Mileageクラスの修正は別チケット)
- このプルリクでは、Makefile.incは変更しない
=> close #40 makeに失敗するため、std::coutをprintfに変更

Makefile.inc
- Makefile.inc ファイルの `APPL_CXXOBJS` を手動で更新しないで済むようにした
- Makefile.inc ファイルの `INCLUDES` に `-I$(ETROBO_HRP3_WORKSPACE)/etroboc_common` を追記
- [sim_extended_api · ETrobocon/etrobo Wiki](https://github.com/ETrobocon/etrobo/wiki/sim_extended_api)
```bash
$ git log
commit 9fdc35e32615f3bbe9d8b827bd3e0ec7f66ff78a (HEAD -> ticket-37)
Merge: 19c6a52 041a614
Author: Takahiro55555 <tkhr.corei7@gmail.com>
Date:   Sat Jun 5 04:45:47 2021 +0900
Merge remote-tracking branch 'origin/ticket-38' into ticket-37
commit 19c6a52d2112b376755029ced704153014732578
Merge: c2e8fe3 63ccedc
Author: Takahiro55555 <tkhr.corei7@gmail.com>
Date:   Sat Jun 5 04:45:40 2021 +0900
Merge remote-tracking branch 'origin/ticket-40' into ticket-37
commit c2e8fe3099da3ed7806d7de440dd560fe5d83192 (origin/ticket-37)
Author: …
```
=> close #37 Makefile.inc ファイルを編集しないで済むようになった

.github/workflows/build-check.yaml, Dockerfile, entrypoint.sh, module/Controller.cpp
- `Dockerfile` の追加
- `entrypoint.sh` の追加
- `.github/workflows/build-check.yaml` の追加
1. ビルド確認に使用する Docker image のタグを作成する
1.1. [ETrobocon/etrobo](https://github.com/ETrobocon/etrobo)の`master`ブランチにおける最新のコミットIDを取得
1.2. `Dockerfile`と`entrypoint.sh`を結合したファイルのハッシュ値を計算
1.3. 上記で取得したコミットIDとハッシュ値を結合し、Docker image のタグとする
2. 上記で作成したタグが付与された Docker image が存在するかどうかを確認する
2.1. 直近ビルドされた Docker image のタグを最大100件取得する
2.2. `1.3.` で作成したタグが存在するか確認し、存在しない場合 Docker image をビルドするためのフラグを立てる
3. Docker image をビルドするためのフラグが立っている場合、ビルドを実行し GitHub Container Registry に Push する
4. ビルドの確認を行う
4.1. GitHub Container Registry にログインする
4.2. GitHub Container Registry から `1.3.` で作成したタグが付与されている Docker image を Pull する
4.3. Docker コンテナに、このGitHubリポジトリのルートディレクトリをマウントし、Dockerコンテナを起動する
4.5. 起動した Docker コンテナの `/entrypoint.sh` …
=> close #43 etrobo環境でのビルド確認をするようにした

module/Controller.cpp, module/Controller.h, module/EtRobocon2021.cpp, test/dummy/etroboc_ext.h
- シミュレータへの競技終了通知を `Controller` クラスから行えるようにした
- Google Test のためにダミーファイルとして `etroboc_ext.h` を追加した
- [ETRoboc_notifyCompletedToSimulator - 競技終了通知](https://github.com/ETrobocon/etrobo/wiki/sim_extended_api#etroboc_notifycompletedtosimulator---%E7%AB%B6%E6%8A%80%E7%B5%82%E4%BA%86%E9%80%9A%E7%9F%A5)
=> close #54 Controller クラスに競技終了通知処理を追加した

module/Controller.cpp, module/Controller.h, module/LineTracer.cpp, test/dummy/Motor.cpp, test/dummy/Motor.h
- ControllerクラスのresetMotorCount()を消去
- test/dummyのMotorのresetを消去
- LineTracer::run()内でresetMotorCount()を使わない処理に変更
resetMotorCount()する度に走行体がカクつく問題を解消した
https://user-images.githubusercontent.com/56989154/122791834-8d55dd80-d2f4-11eb-97fc-1bef99a41ecb.mp4
https://user-images.githubusercontent.com/56989154/122792141-d5750000-d2f4-11eb-9ae4-df2e9334bc05.mp4
=> close #70 モータをリセットしないようにする

module/LineTraceArea.cpp, module/LineTraceArea.h
LineTraceArea.hのLRコースのサイズを変更
LineTraceArea.cppのLRコースのPIDパラメータを調整、区間の距離を変更
https://user-images.githubusercontent.com/83002406/123203629-9fe93600-d4f1-11eb-9209-197c85288dbf.mp4
https://user-images.githubusercontent.com/66076307/123535494-13dc4600-d75f-11eb-9a21-f2462072ca5a.mp4
全体の明るさ、影の方向、Lコーススポットライト、Rコーススポットライトの明るさをそれぞれ最小(0)、最大(3)にして（16パターン）各条件で10回ずつ走らせる（計160回）
Lコース初期位置
　X:3.53, Y:0, Z:-16.52, ROT:90
Rコース初期位置
　X:-3.53, Y:0, Z:-16.52, ROT:-90
Lコース
・**平均タイム:18.486(s)(n=154)**
・**走破率:96.250(%)(n=160)**
備考:6/160のコースアウトが見られた、スタートやゴール前カーブで回転し始めて進まないケースや、ゴール前直線でのコースアウトであった
Rコース
・**平均タイム:18.507(s)(n=156)**
・**走破率:97.500(%)(n=160)**
備考:4/160のコースアウトが見られた、コースアウトしたケースはすべてゴール前直線でコースアウトしていた
LRコース
・***平均走破率:96.875(%)***
・タイムは割愛
備考:ターミナル上のタイムよりシミュレータ上のタイムが少し早くなっているので実際のタイムはもう少し早いと考えられます(0.2sくらい？) …
=> close #59 ライントレースエリアの検証、PID調整

module/ColorJudge.cpp, module/ColorJudge.h, module/Measurer.cpp, module/Measurer.h, test/ColorJudgeTest.cpp, test/MeasurerTest.cpp, test/dummy/ColorSensor.cpp, test/dummy/ColorSensor.h
- Measurerクラスに、getColorId()を追加
- ColorJudge.h, ColorJudge.cpp を作成
- MeasurerTest.cpp, ColorJudgeTest.cpp を作成
- ColorSensorクラスに色識別に関するダミーを追加
- 1 : シミュレータの環境設定で初期位置を変えながら、ColorJudgeクラスを使って色を表示させた。
- 2 : シミュレーターの環境設定で環境光（4パターン）と影の位置（4パターン）をそれぞれ条件を変更させ、正しく色を取得できるか確認した。
以下、実験した範囲では正しく判定できていた
- Lコース上辺　右から　青赤緑
- Lコース上辺　右から　青赤緑 
- Rコース下辺　左から　青赤緑
- Lコース下辺　右から　青赤緑
- Rコース上辺　左から　赤緑黄
- Rコース下辺　左から　青赤緑
- Lコース中辺　下から　赤緑
- Lコース右辺　下から　青木赤 
- Lコース左辺　下から　緑青黄
- Lコース左辺　上から　黄青緑
以下、実験した範囲では正しく判定できていた
- 環境光1 影の位置1
- 環境光1 影の位置2
- 環境光1 影の位置3
- 環境光1 影の位置4
- 環境光2 影の位置1
- 環境光2 影の位置2
- 環境光2 影の位置3
- 環境光2 影の位置4
- 環境光3 影の位置1
- 環境光3 影の位置2
- 環境光3 影の位置3
- 環境光3 影の位置4
- 環境光4 影の位置1
- 環境光4 影の位置2
- 環境光4 影の位置3
- 環境光4 影の位置4
- Lコース上辺　右から　青赤緑
https://user-images.githubusercontent.com/83441177/123477312-d2517b00-d638-11eb-8f4e-0e1cb736c …
=> close #68 色を取得・識別する

module/LineTracer.cpp, module/LineTracer.h
- LineTracerクラスに、白黒を識別している間、ライントレースするrunByColor()を追加
- 「色を取得・識別する」がないため、コンパイル・テストは通らない。(あれば通った)
- 「色を取得・識別する」を反映し、テストした
- ライントレースエリア(ゴール付近の青線まで)を3回ライントレースした
- ブロックビンゴエリアにて、ライン上の各色(黄、赤、青、緑)について、10回ずつライントレースした
- ライントレースで、ライントレースエリアを完走できた。
- いずれも、白黒以外の色に入った時点で停止した。
https://user-images.githubusercontent.com/83441177/123540592-c79eff00-d77a-11eb-8896-dddcf6edbe22.mp4
=> close #61 白黒以外を判定するまでライントレースする

.github/workflows/google-test.yaml
プルリクを出した後、再度 Push を行うと Google Test が2つ同時に実行される問題を解消した。
細かな変更点は以下の通り。
- workflow の起動条件から `pull_request` を削除
- 実行環境を Ubuntu 18.04 から Ubuntu 20.04 に変更
- 無駄な cmake のインストール処理を削除（GitHub Actions の実行環境に最初から用意されていた）
- jobの名前?を`build` -> `test` に変更
このプルリクをもって動作テストとする。
=> close #48 Google Test を実行する workflow のトリガーに関して

module/StraightRunner.cpp, module/StraightRunner.h, test/StraightRunnerTest.cpp
直進・後退するクラス（Straighter）を作成。
指定距離を直進・後退する関数(straight())を作成。
白黒以外を検知するまで直進・後退する関数(straightByColor())を作成。
ブロックビンゴエリアに走行体を設置し、走行体が色を認識するまで直進（後退）させる。
指定した距離（1050mm）を直進（後退）する。
白黒以外の色を認識すると走行体が止まった（直進と後退）
指定した距離（1050mm）を進んだ（直進と後退）
ただし、多少右へのずれあり。
https://user-images.githubusercontent.com/83230897/123544256-60d71100-d78d-11eb-9f3c-4cd3cbf95d34.mp4
https://user-images.githubusercontent.com/83230897/123544251-5ddc2080-d78d-11eb-9e19-02f629e5d938.mp4
https://user-images.githubusercontent.com/83230897/123545555-8f57ea80-d793-11eb-983e-549197b5bf9b.mp4
https://user-images.githubusercontent.com/83230897/123545845-23768180-d795-11eb-99e0-02d3baa48d06.mp4
=> close #67 直進・後退する

module/BlockSelector.cpp, module/BlockSelector.h
- BlockSelectorクラスのメンバにある配列の初期化をコンストラクタで行うように変更
```
bool OPEN_CIRCLE_ID[static_cast<int>(BLOCK_ID::ID7) + 1][static_cast<int>(CIRCLE_ID::ID7) + 1] = {
{ T, T, T, T, F, F, F, F },
{ F, T, T, F, T, F, F, F },
{ T, T, F, T, F, T, F, F },
{ T, T, T, T, T, F, T, T },
{ T, T, F, T, T, T, T, T },
{ F, F, T, F, T, F, T, T },
{ F, F, F, T, F, T, T, F },
{ F, F, F, F, T, T, T, T }};
```
のように書き換えると解決したらしいので，STLコンテナが何か悪さをしている？
BlockSelectorクラスと同様に，宣言時に配列の初期化をするサンプルコードで試したところ，特にエラーは出なかったため，シミュレータ環境下での問題だと考えられる．
サンプルコードは下図に示す．
=> close #99 シミュレータが起動しない問題の解決

module/StraightRunner.cpp, module/StraightRunner.h
StraightRunnerクラス
- 黒白を検知するまで直進するメンバ関数を追加
- 各メンバ関数に、左右のモータカウントを合わせる処理を追加
- 各メンバ関数に、指定値に向けて、徐々に加速する処理を追加
一定距離(ビンゴのマスの辺2.5本分)をPWM値、50, 100でそれぞれ10回走行し、黒線と比べ、どれだけずれているかを見る。
真上から見た際の、黒線との角度の差(deg)を計測した。
PWM=50 誤差単位[deg]
| 修正前 | 修正後 |
| ------------- | ------------- |
| 3.0 | 1.4 |
| 3.5 | 2.1  |
| 2.0| 1.1 |
| 2.0| 2.1  |
| 4.6  | 0.3  |
| 4.0  | 2.3  |
| 0.0  | 0.5  |
| 2.8  | 1.0  |
| 1.4  | 0.8  |
| 1.0  | 0.2  |
修正前平均：2.43 deg
修正後平均：1.18 deg
PWM=100 誤差単位[deg]
| 修正前 | 修正後 |
| ------------- | ------------- |
| 4.5  | 2.2 |
| 39.2 | 4.2 |
| 3.5 | 2.6 |
| 13.2 | 0.5 |
| 7.6 | 1.3 |
| 34.1 | 2.3 |
| 25.2 | 1.0 |
| 5.5 | 1.2 |
| 19.8 | 1.3 |
| 47.8 | 1.3 |
修正前平均：20.04 deg
修正後平均：1.79 deg
PWM=50のとき
修正前
https://user-images.githubusercontent.com/83441177/126912123-0606cb19-30c5-4b23-8cb0-dae8bbf46567 …
=> close #96 直進の精度調整

module/ColorJudge.cpp, module/ColorJudge.h, test/ColorJudgeTest.cpp
ColorJudge.hのしきい値を変更
ColorJudge.cppの処理を修正
ColorJudgeTest.cppから不適切なテストケースを削除
- シミュレータ環境で、走行体を走らせ取得したRGB値をcsvをとして保存
- csvから、ブロックビンゴエリアのマップを再現(html)
- csvから、色を識別し、マップを再現
- マップを比較
環境①
全体の明るさ: 最低
スポットライト：最低
測定値
精度調整前
精度調整後
環境②
全体の明るさ: 最低
スポットライト：最高
測定値
精度調整前
精度調整後
環境③
全体の明るさ: 最高
スポットライト：最高
測定値
精度調整前
精度調整後
=> close #95 色識別の精度調整

module/Rotation.cpp, module/Rotation.h, test/RotationTest.cpp, test/StraightRunnerTest.cpp
- Rotation.cppの回頭とピボットターンに、目標値に近づくにつれPWM値を徐々に小さくしていく処理を追加
- 回頭での両方のタイヤを止める条件を片方の足に合わせた
- 回頭とピボットターンの描く円の直径を別々に定義した。回頭がTREAD、ピボットターンがDIAMETER。
https://user-images.githubusercontent.com/83375723/126997234-030a38ea-dc09-40e3-bde5-96b3efb82ad9.mp4
https://user-images.githubusercontent.com/83375723/126997736-eacbd46b-c906-4607-b78e-56fd01a0a349.mp4
https://user-images.githubusercontent.com/83375723/126997955-a9a421f5-5feb-4c81-91b6-1187091373f1.mp4
- 回頭はPWM値40で４回動かした
- ピボットターン（前進）PWM値50で4回動かした
- ピボットターン（後進）PWM値50で4回動かした
- PWM値をある程度限定すれば高い精度で回れると思う。
=> close #97 回頭・ピボットターンの精度調整

module/Motion/ArmMotion.cpp, module/Motion/ArmMotion.h
- ArmMotion.h から Pid.h のインクルードを削除
- ArmMotion.cpp から、出力をPIDでなく、目標値との差で算出するように変更
https://user-images.githubusercontent.com/83441177/130080346-a1446656-efea-4832-92fc-9cd776d6ef28.mp4
=> close #144 アーム水平からPIDの処理を排除

module/BingoMotion/BlockThrower.cpp, module/BingoMotion/BlockThrower.h, module/BingoMotion/ToCrossMotion.cpp, module/Motion/ArmMotion.cpp, module/Motion/ArmMotion.h, test/dummy/Motor.cpp, test/dummy/Motor.h
- 投げ入れ設置クラスで回頭と投げる動作を同時に行うように変更した
- 10回動かして動作時間・誤差（角度）・投げ入れの成功を確認する
|  -  |  -  |
|  -  |  -  |
[動作時間と誤差](https://docs.google.com/spreadsheets/d/1Go2aX7Qr2n07WcpFk1I_oKR1XRqddYP3sxdA602SNZU/edit#gid=0)
- 設置位置にばらつきはあるが、動作テストではすべてブロックサークル内に収まっていた。
- まれにピボットターンのような挙動をすることがあった。（原因究明中。動作環境の問題？手元で何度か動かしてみていただけると助かります。）
投げ入れ右
https://user-images.githubusercontent.com/83354922/130746997-18ab0aa9-71c9-4aa9-b8ff-129a76f52ea9.mp4
投げ入れ左
https://user-images.githubusercontent.com/83354922/130747077-e06cdf89-d714-44d8-ae6c-8dbdbf761b62.mp4
=> close #137 設置動作の改良

module/RoutePlanner/RoutePlanner.cpp, test/RoutePlannerTest.cpp
- RoutePlannerにて、取得経路と運搬経路を合わせたものを1経路として保持するように変更
- 取得経路の末尾と設置経路の先頭が重複していたためfor文の添え字を変更
- テストコードの変更
~# 動作テスト~
各indexに取得→設置までの経路が格納されていることを実際に経路を表示して確認、およびテストコードによる確認
~## 実験データ~
~|  修正前  |  修正後  |~
~| ---- | ---- |~
~|  -  |  -  |~
~|  -  |  -  |~
**テストコードのpassに成功**
経路を表示したものを添付
~## 添付資料~
本チケットでの最短経路とticket-152の最短経路は異なるものになる
=> close #153 取得経路と運搬経路を合体

.gitignore, scripts/sim-test-wsl.sh, sim-test-all.sh, sim-test-cancel.sh
- シミュレータの自動実行ツールにキャンセル機能を追加
WSLで新たな端末（ターミナル）を立ち上げて以下のコマンドを実行した後、終了するまで待つ。
```
cd ~/etrobo/workspace/etrobocon2021
./sim-test-cancel.sh
```
手元の環境で動作を確認
https://user-images.githubusercontent.com/31930148/131489427-288716b2-dd73-40b2-bdc8-810ba4be1dc8.mp4
=> close #170 シミュレータの自動実行ツールにキャンセル機能を追加する

scripts/sim-test-wsl.sh, sim-test-all.sh
- ループが回る毎に、キャプチャ画像を都度削除するようにした
- ついでに、シミュレーションが早く終了すると走行開始前の映像が後半部分にくっついてくる問題を解消
- ローカル環境で実際に動作させた
ツール実行前のキャプチャ画像ディレクトリの親ディレクトリと実行後の親ディレクトリに変化が無いことを確認。
つまり、ツールによって生成された一時ディレクトリ（及びファイル）はツールによって削除されたことを確認。
具体的には以下のコマンドを実行することによって確認をした。
```
ls /tmp/ > ls-tmp-before.txt
./sim-test-all.sh ; ls /tmp/ > ls-tmp-after.txt
diff ls-tmp-before.txt ls-tmp-after.txt 
```
以下時示すキャプチャ映像から問題の解消を確認。
https://user-images.githubusercontent.com/31930148/131846549-d13c6bbd-6614-45ea-b971-4074585a72dd.mp4
https://user-images.githubusercontent.com/31930148/131846596-29ef3771-0ba7-4c9b-8dcd-5ada660d15ec.mp4
=> close #175 シミュレータ自動実行ツールによって生成されたキャプチャ画像の削除機能を追加する

.github/workflows/sim-test.yaml
- ~~[ ] clang-format している~~
- ~~[ ] コーディング規約に準じている~~
- CIのシミュレータテストにおいて、ビンゴエリアの結果を取得・反映できるようになった
- シミュレータテストを左右のコースで複数回実行できるようになった
- GitHub の API を使うことによって、CIのテスト結果をコメントを逐次アップデートする形で通知することが出来るようになった
- テスト実行中に他のシミュレータテストのリクエストが来た場合、それ以降のテストを実行しないようにした
- テスト終了時にキャプチャファイルなどを都度削除し、ディスク使用量の削減に努めた
このプルリクの結果を参照すること。
以下、時系列順
1. プルリクエストを出したことにより、シミュレータテストが開始される
2. 上記のシミュレータテストが実行されている途中で、新たな変更をPushしたことにより新たなシミュレータテストのリクエストが発生するが、マシンは1台しかないため待ち状態が発生する
3. すると、`1.`のシミュレータテストは待ち状態を検知し、以降のシミュレータテストを中断する【1つ目の結果】
4. `2.`で待ち状態になっていたシミュレータテストが開始される
5. 上記のテストの途中で他のシミュレータテストのリクエストが発生しなかったため、最大試行回数(4回)分のテストを行いテストを終了する【2つ目の結果】
（以下略）
~~動作テストが完了次第、シミュレータの最大試行回数を20回に設定予定（現在は簡単のため4回）。~~
何故か知らないけど、GitHubのコメント（シミュレータテストの結果）をアップデートするとSlackへ転送されたコメントもアップデートされる模様
シミュレータテストが実行中の場合、当該コメントに以下のように実行中である旨を記述している。
> …
=> close #146 CIのシミュレータテストにビンゴエリアの結果を反映する

module/BingoMotion/BlockThrower.cpp, module/BingoMotion/DirectionChanger.cpp, module/Motion/Rotation.cpp, test/RotationTest.cpp
- 回頭動作のパラメータ調整
- 方向転換後に直進する処理を修正
- 投げ入れ設置時の回頭動作を修正
投げ入れ設置、ピボットターン設置それぞれについて、「設置動作→方向転換→交点間移動」を3連続で行い、正常に動作できるかを確認する。
テストルート完走率(3連速で設置できた率)
| 動作 |  修正前  |  修正後  |
| ---- | ---- | ---- |
|  投げ入れ設置  |  50%  |  60%  |
|  ピボット設置  |  0%  |  44%  |
https://user-images.githubusercontent.com/83441177/132138564-92bc7d2b-1510-4e2b-bb9a-49c5bafadf7d.mp4
https://user-images.githubusercontent.com/83441177/132138569-c7935c85-58fe-4b16-9d5a-8d0d7fa22c82.mp4
https://user-images.githubusercontent.com/83441177/132138590-a1ad7f19-3686-4b94-831c-08ae68f4846e.mp4
https://user-images.githubusercontent.com/83441177/132138598-d8de6b82-47fb-408a-b099-93c19a56311c.mp4
=> close #158 方向転換の精度調整

module/BingoMotion/BlackBlockCarrier.cpp, module/BingoMotion/BlackBlockCarrier.h, module/Motion/StraightRunner.cpp, module/Motion/StraightRunner.h
黒ブロックの設置動作を旋回設置から直進→ピボットターン→直進の動作に変更
以下の要点に着目し、検証を行う。
- 黒ブロックを設置できているか
- 設置動作後にビンゴ動作を行えるか
黒ブロックを設置できる確率 75%
黒ブロックを設置できるかつ設置後にビンゴ動作を行える確率 62%
https://user-images.githubusercontent.com/62526141/132176139-5d2f6fa0-38f6-4916-8166-eeafa025abd0.mp4
https://user-images.githubusercontent.com/62526141/132176270-5bb2eab2-e4b3-4352-80a7-4b5f02322b32.mp4
https://user-images.githubusercontent.com/62526141/132176389-63c0ec73-01b0-49e8-b496-4975a8022931.mp4
=> close #189 黒ブロック運搬の精度調整

module/LineTraceArea.cpp
ライントレースエリアのPID
- Lコース
| 番号 | 全体の明るさ | 影の方向 | スポットライトLの明るさ | スポットライトRの明るさ | コース | 走行時間 | 設定ファイル名 |
| ---- | ----------- | ------- | --------------------- | --------------------- | ------ | ------- | ------------- |
| 1 | 2 | 1 | 1 | 1 | Left | 17.216 | sim-settings/l/01.json |
| 2 | 2 | 1 | 1 | 1 | Left | 17.166 | sim-settings/l/02.json |
| 3 | 2 | 1 | 1 | 1 | Left | 17.266 | sim-settings/l/03.json |
| 4 | 2 | 1 | 1 | 1 | Left | 17.199 | sim-settings/l/04.json |
| 5 | 2 | 1 | 1 | 1 | Left | 17.316 | sim-settings/l/05.json |
| 6 | 2 | 1 | 1 | 1 | Left | 17.249 | sim-settings/l/06.json |
| 7 | 2 | 1 | 1 | 1 | Left | 17.249 | sim-settings/l/07.json |
| 8 | 2 | 1 | 1 | 1 | Left | 17.199 | sim-settings/l/08.json |
| 9 | 2 | 1 | 1 | 1 | Left | 17.233 | sim-settings/l/09.json |
| 10 | 2 | 1 | 1 | …
=> ticket #193 パラメータ調整

module/RoutePlanner/BlockSelector.cpp, module/RoutePlanner/RouteCalculator.cpp, module/RoutePlanner/RouteCalculator.h, module/RoutePlanner/RoutePlanner.cpp, test/MotionConverterTest.cpp
- ピボットターン設置をし終わった際の走行体の向きをブロックサークルでの向きとする
- 閉路がある場合に探索が終わらなかったのを、一度訪れた座標を再度訪れないようにして閉路があっても探索が終わるように変更
**ピボットターン設置の動作を調整しないと本チケットは正常な動作を行うことができない**
実際に経路を表示する/閉路があるパターンで動作を正常に終えるか動作を表示する
**閉路による問題**
[探索が終わらず動作が始まらないパターン](https://etrobocon2021.moyashi.dev/01/results/2021-09-07/15-29-33/5211a69f3109f66d17fdc13eb1d8e46cfd865c63-16.mp4)
[本チケットのコードでの確認](https://user-images.githubusercontent.com/66076307/132348590-a5db34a9-29ae-438a-b939-5fd731189a76.mp4)
**ピボットターン設置後の方向転換の確認**
変更前
変更後
=> close #202 ピボットターン設置の後ブロックサークルの方向を向いて終了しても経路計画が行えるようにする

module/RoutePlanner/RouteCalculator.cpp, module/RoutePlanner/RouteCalculator.h
- スタートノードを未探索として探索を開始していたのを、探索開始時点で探索済みとするように変更(スタートノードの隣接ノードを探索した際に探索済みとしているため今までのコードでも探索は終わっていた）
=> close #210 経路計算でスタートノードの初期設定が間違っているのを修正

module/RoutePlanner/BlockSelector.cpp, module/RoutePlanner/BlockSelector.h, module/RoutePlanner/DestinationList.cpp, module/RoutePlanner/DestinationList.h, module/RoutePlanner/RoutePlanner.cpp
- BlockSelectorクラスのselectBlock関数に、運べるブロックがない場合に運搬先を変えることで運搬できるブロックを選択するような処理を追加
- Destinationクラスでもう１つの運搬先も保持するようにし、運搬先の入れ変え（本来の運搬先と選ばれなかった運搬先）を行う関数を追加
詰みパターンでも攻略ができるかを検証、BlockSelectorのテストコードにて入れ替えが必要ない場合は従来の処理のままであることを確認
変更前
https://etrobocon2021.moyashi.dev/01/results/2021-10-14/16-06-28/da55db21f7e546654457eae6ab63692a6776cba2-42.mp4
変更後
https://user-images.githubusercontent.com/66076307/139032034-311b833e-5164-43a8-9e16-15404f7c2cd9.mp4
=> close #239 ブロックを運搬できないパターンを攻略するアルゴリズムの実装

module/BingoMotion/InCrossLeft.cpp, module/BingoMotion/InCrossRight.cpp, module/RoutePlanner/MoveCostCalculator.cpp, module/RoutePlanner/MoveCostCalculator.h, module/RoutePlanner/RouteCalculator.cpp
試走会で、右左折動作中にブロックを放してしまったシーンがあったため、PWM値を下げた。
CI、手元環境での再現率は低い。
=> close #235 右左折の精度調整

module/BingoMotion/BlockPivotTurn.cpp, module/BingoMotion/BlockPivotTurn.h
動作の変更
直進→45度ピボットターン→85度回頭→サークルの中心まで移動→元の位置まで戻る
CI上で起きていたブロック設置動作後にはねる動きを修正した。
設置動作後の方向転換が正常に動くように最初に直進する距離のパラメータの調整を行った。
手元環境で左右ピボットターン設置を各10回ずつの計測を行う
CI上での動作を確認
左ピボットターン
|時間(s)| 角度の差(deg)|
| ------------- | ------------- |
|5.654713|3.2|
|5.614579|5.1|
|5.684998|1.0|
|5.654998|3.6|
|5.640020|1.0|
|5.635011|3.1|
|5.630023|4.1|
|5.750015|1.4|
|5.630018|3.8|
|5.650012|4.7|
右ピボットターン
|時間(s)| 角度の差(deg)|
| ------------- | ------------- |
|6.040572|2.5|
|6.070039|4.9|
|6.120022|2.0|
|6.130004|0.1|
|6.070027|0.5|
|6.100025|0.4|
|6.040037|0.9|
|6.060025|0.6|
|5.974998|4.7|
|6.120018|0.3|
修正前と修正後の比較
左ピボットターン設置
| 修正前時間(s) |修正後時間(s) |修正前の角度の差(deg)| 修正後の角度の差(deg)|
| ------------- | ------------- | ------------- | ------------- |
|       5.7144688          |       5.6544387           |          2.47 …
=> close  #213 ピボットターン設置の調整
